### PR TITLE
GEM-7489: Adds example scripts.

### PR DESCRIPTION
**Pull request by jake-at-work**
* Example run-gfsh.sh
* Example start-locator.sh
* Example start-server.sh

### CODE REVIEW

**Review by kohlmu-pivotal — COMMENTED** [review]
I don't know if we should be explicitly setting values in this script.

I assume GemFire properties, like name, bind-addresses, etc should be either set from a properties file OR cmd-line. But if we use cmd-line we could not validate the args to they are passed through and have the underlying fail. 

GEMFIRE_HOME should check for env variable else fail. OR we default to a relative path (risky).

Could we possibly expose APPLICATION_HOME, that way the customer/user can select a single location and the system does a wildcard inclusion.

JAVA_OPTIONS would require a little more work, as having customers/users alter the script when starting servers/locators is too hard. So an ability to provide JVM args via cmd-line that could potentially override the defaults would need to be added

**Comment by jake-at-work** [comment]
I think you might be missing the point of these examples. These are examples of how to write scripts to directly start members or wrapper scripts around gfsh. We have customers that write these scripts because frankly `gfsh` is horrible for starting members in production. They aren't meant as product. We should make a product script... but that is for another fight.

So no, these script examples should not assert that certain properties, environment variables, etc. be set. What the customer wants to set in these are not our concern outside of them getting the bootstrapping correct.

**Comment by kohlmu-pivotal** [comment]
That makes more sense.

**Review by kohlmu-pivotal — APPROVED** [review]
LGTM.

Given that the start-server.sh does not contain `locators` property, we might add that to the README file, showing HOW to use the scripts. OR we have to add the `locators` property to the start-server script

**Comment by jake-at-work** [comment]
> LGTM.
> 
> Given that the start-server.sh does not contain `locators` property, we might add that to the README file, showing HOW to use the scripts. OR we have to add the `locators` property to the start-server script

Oh, good call. That would have been a smart thing to include in the examples. 🤦

**Comment by jake-at-work** [comment]
Sadly locators addresses are not a first class configuration argument. 😢

**Pull request merged**
